### ISSUE TITLE
Add package in Homebrew or pip .

### ISSUE THREAD

**Issue by saru95** [saru95/gitini#2]
Make this script installable using pip or homebrew . Take care of user parameters and get rid of install.sh file .

**Comment by vitorgalvao** [comment]
Unfortunately, you won’t have luck adding this to Homebrew. At least not to the main repository in its current state.

Reason being there’s a minimum popularity threshold for packages to be accepted, and this project has too few stars to pass.

**Comment by saru95** [comment]
pip maybe then .

**Comment by zoidbergwill** [comment]
You could always have your own tap for custom formulae for homebrew, which would just be another repo to have all your homebrew formulae.

**Comment by jvalinsky** [comment]
If you want your own tap for custom homebrew formulas, make a new github repo named homebrew-tap and put any formula ruby scripts in there for any of your projects. I made a formula for gitini that I will submit as a pull-request once you do that. Then one will be able to do 'brew tap saru95/tap && brew install <formula name>' to install a formula from your tap repo.

**Comment by saru95** [comment]
@jvalinsky Here you go , https://github.com/saru95/tap

**Comment by jvalinsky** [comment]
the name has to be prefixed with "homebrew-", so it needs to be "hombrew-tap".

**Comment by saru95** [comment]
Done : https://github.com/saru95/hombrew-my-tap

**Comment by jvalinsky** [comment]
@saru95 I added the homebrew formula for gitini in the other [repo](https://github.com/saru95/hombrew-my-tap). You should be able to do brew tap saru95/my-tap && brew install gitini.

**Comment by saru95** [comment]
Sure mate . Thanks for the PR !
